baseurl = "http://tanksuzuki.com/"
languageCode = "en"
title = "jhas.site"
disqusShortname = "jhas"

[Params]
subtitle = "I would like to be a layer 3 switch."
github = "https://github.com/648759528ass"
profile = "/images/profile.png"
copyright = "Written by jhas"
analytics = "UA-XXXXXXXX-X"